name: Golang Test and Build
on:
  push:
    branches: [main]
  pull_request: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: [1.21.x]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: go.sum
      - name: Test
        run: go test -v ./... -timeout 2m
