name: Golang Test and Build
on:
  push:
    branches: [main]
  pull_request: {}
  schedule:
    - cron: "0 0 * * 6"
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        go-version: [1.20.x, 1.21.x, 1.22.x]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          cache-dependency-path: go.sum
      - name: Test
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./... -timeout 2m
      - name: Upload coverage reports to Codecov
        if: ${{ matrix.go-version == '1.22.x' && matrix.os == 'ubuntu-latest' }}
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
